### PR TITLE
Change location of data scripting to its own repo

### PR DESCRIPTION
**Pull request by switzersc**
I recently started down the path of adding data scripts to the Healthify app repo and some concerns emerged. First, if the script is not contained within some sort of class, or other object, it risks being eagerly loaded and being run when the app starts, which would not be desirable. This then caused me to go down the path of trying to impose some artificial object-orientedness to the script, when that is unnecessary and not always preferable. Furthermore, keeping the script code in the app repo in my mind pressures me to think about reusability, OOPiness, testability, etc, when I believe we've all agreed that these data scripts are one-offs and we shouldn't be concerned with these aspects. 

I have therefore created a new repository for data scripts to live in and propose this change to keep scripting code separate from our app code. I believe this will reduce the risk of accidentally loading the scripts when we don't need them as well as appropriately keep the styles/approaches/structures separate physically when they are so separate in concept and procedure.

### CODE REVIEW

**Comment by amar47shah** [comment]
LGTM!

**Comment by KrishnaKulkarni** [comment]
There are some advantages of having the scripts live in the app repo if they are going to be run in the app's database. The big ones in my mind is testing and development, which are much easier if you can straightforwardly access our Models and database.

That said, I think it's also fine to keep this in its own repo

**Comment by amar47shah** [comment]
@healthify/development:

If there are no objections, I recommend merging now. We are already using the [data-scripting repo](https://github.com/healthify/data_scripting/pulls).

**Comment by switzersc** [comment]
Pinging @dleve123 and @aaronagray to put some eyes on this.

**Comment by dleve123** [comment]
I think it's advantageous to leave data scripts in the main codebase because:
1. The ability to re-use models, making it easier to test these scripts (as Krishna said).
2. I imagine that, sometimes, data scripts will relate to schema migrations. Moreover, if we model data scripts as migrations, then we can capture the potential time dependency between a schema migration and a data migration on each other using Rails' migration time-stamping feature.
3. It seems like a lot of our data migration protocol mimics some existing features of Rails' migrations, specifically having `up` and `down` directions, running all SQL in transactions, and, as such, is a good fit for data scripts to be a Rails' migration.
4. Ease of run-time. As opposed to needing to copy and paste a file around to run a script (as described [here](https://github.com/healthify/data_scripting/tree/master/2016-11-07-remove-orphaned-addresses#running-the-script-on-the-remote-server)), we can run using a `rake db:migrate`.
5. Audit-ability: Rails' migrations persist the fact that a migration was run within a `schema_migrations` table, providing an audit trail of data migrations. 

> First, if the script is not contained within some sort of class, or other object, it risks being eagerly loaded and being run when the app starts, which would not be desirable. 

Out of curiosity, when did this problem manifest itself?

**Comment by switzersc** [comment]
Based on your comments @dleve123, it sounds like you’re suggesting that we go down a completely different path that what’s in the current guides (and not just what’s proposed in this PR). To confirm, you are suggesting that we add data migrations to the `db/migrate` directory along with schema change migrations, so that they are automatically run during any deploy or `rake db:migrate`, with the option to rescue the migration with the db:rollback command.

I disagree with that direction, however, for the following reasons:
1. It removes the developer from the process of ensuring that the changes that are made are what we expect. Furthermore, if we write the script to raise exceptions to alert the developer when something went wrong (“you may choose to move the assertions of your tests into the script itself as assertions that will trigger a transaction rollback if they fail.”), then the exceptions will be raised during the deploy process, blocking the deploy pipeline until it is fixed and causing the scripting process to take longer than it would otherwise.
2. Your point about audibility is interesting, especially in light of recent times when we actually went back through the `migrate` directory to remove data and schema migrations that we didn’t need hanging around anymore or that might have led to problems when loading/migrating the db schema in different environments. While the timestamp of migrations run through the Rails migration feature will probably continue to exist in the database (unless someone removes them, which I believe we might actually have done a few months ago with certain migrations), removing migrations from the codebase makes it much harder to find out what exactly the change was, requiring lots of digging and searching through git history. Furthermore, the fact that we’ve already wanted to remove data migrations to me suggests that they don’t belong in the codebase. I think a dedicated repository with dates, READMEs, never-deleted scripts, and process around code review, QA, and merging upon deploy solves this problem equally well if not better than automated timestamps through the `migrate` process.
3. It reduces the flexibility we have with picking the right tool for the job. Using only Rails migrations means that everything we do must be done in Ruby. If a developer would prefer to write the script in straight SQL — which has happened before and I think will continue to be a preference of some people on the team – that dev would have to bloat their script with ActiveRecord wrappers unnecessarily. Furthermore, data migrations may not always have to do with the Rails app’s database. 
4. Tools like Code Climate will become increasingly inaccurate and unused because scripts are inherently going to do things that go against CC’s idea of reusability, limited assignments per method, method length, etc. This concern speaks more broadly to the idea that this scripting code really has nothing to do with our app code and just adds bloat to the app repository.

I think other people can also speak to why we moved away from doing data migrations per the Rails migrate pipeline, as it has been the norm recently to do these migrations separately. I do think though that this is unrelated to the PR at hand, which simply seeks to keep the established protocol but move the migrations from a new `db/migrations` (outside of the Rails migration pipeline) directory to a separate repository. If you want to change the protocol that dramatically, I think it’s worth creating a new pull request with your recommended protocol to continue that discussion.

**Comment by dleve123** [comment]
@switzersc I think these are good points! It wasn't top of mind when I was writing my comment that the current state is writing scripts in a separate directory, not within Rails migrations. Given this initial state, and also that we're increasingly going to be affecting non-app DBs (like Segment's DB). I think your diff is an improvement.

Re audit-ability: I think, by default, having an audit trail of database migrations, even if some are audit events are deleted, is better than no audit trail at all.

Nonetheless, 👍

**Comment by KrishnaKulkarni** [comment]
As old as this is, it is accurate and was approved, so I am merging! @switzersc

**Pull request merged**
